services:
  caddy:
    image: caddy:2-alpine
    container_name: caddy
    ports:
      - "80:80"
    volumes:
      - ./conf:/caddy/conf
      - ./site:/caddy/srv
      - caddy_data:/caddy/data
      - caddy_config:/caddy/config
    networks:
      - smartcity-net
      
  app1:
    build: ./flask/app1
    container_name: app1
    networks:
      - smartcity-net

  app2:
    build: ./flask/app2
    container_name: app2
    networks:
      - smartcity-net

volumes:
  caddy_data:
  caddy_config:

networks:
  smartcity-net:
    driver: bridge